# Generated by Django 5.1.7 on 2025-03-07 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='home.fooditem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='home.restaurants')),
            ],
            options={
                'unique_together': {('restaurant', 'food_item')},
            },
        ),
    ]
